import { Substance, UserSettings, CustomEffect } from './types';

export const DEFAULT_SUBSTANCES: Substance[] = [
  { 
    id: 'caffeine', 
    name: 'Kofein', 
    halfLife: 5, 
    tmax: 0.75, 
    bioavailability: 100, 
    color: '#8B4513', 
    icon: 'coffee', 
    unit: 'mg', 
    price: 2, 
    step: 50, 
    category: 'stimulant', 
    onset: 15, 
    offset: 4, 
    toxicity: 10, 
    toleranceRate: 15, 
    toleranceReset: 7, 
    metabolismCurve: 'standard', 
    metabolismRate: 1, 
    absorptionRate: 1, 
    beta: 0.14, 
    ka: 4, 
    comedownEnabled: false, 
    comedownDuration: 2, 
    comedownIntensity: 3, 
    comedownSymptoms: ['Únava', 'Bolest hlavy'], 
    strains: [], 
    effects: [
      { type: 'Stimulace', intensity: 7, onset: 0.25, duration: 4, valence: 'positive' }, 
      { type: 'Kognice', intensity: 6, onset: 0.5, duration: 3, valence: 'positive' }, 
      { type: 'Diuréza', intensity: 5, onset: 0.5, duration: 3, valence: 'neutral' }
    ], 
    interactions: [], 
    description: 'Nejrozšířenější stimulans na světě' 
  },
  { 
    id: 'nicotine', 
    name: 'Nikotin', 
    halfLife: 2, 
    tmax: 0.17, 
    bioavailability: 80, 
    color: '#556B2F', 
    icon: 'leaf', 
    unit: 'mg', 
    price: 8, 
    step: 0.5, 
    category: 'stimulant', 
    onset: 5, 
    offset: 1, 
    toxicity: 5, 
    toleranceRate: 25, 
    toleranceReset: 3, 
    metabolismCurve: 'standard', 
    metabolismRate: 1, 
    absorptionRate: 1, 
    beta: 0.35, 
    ka: 20, 
    comedownEnabled: true, 
    comedownDuration: 1, 
    comedownIntensity: 6, 
    comedownSymptoms: ['Chuť k jídlu', 'Podrážděnost', 'Touha'], 
    strains: [], 
    effects: [
      { type: 'Stimulace', intensity: 6, onset: 0.08, duration: 0.5, valence: 'positive' }, 
      { type: 'Relaxace', intensity: 4, onset: 0.17, duration: 0.5, valence: 'positive' }, 
      { type: 'Chuť k jídlu', intensity: -5, onset: 0.17, duration: 1, valence: 'negative' }
    ], 
    interactions: [], 
    description: 'Vysoce návykové stimulans' 
  },
  { 
    id: 'alcohol', 
    name: 'Etanol', 
    halfLife: 4, 
    tmax: 0.5, 
    bioavailability: 80, 
    color: '#FFD700', 
    icon: 'wine', 
    unit: 'g', 
    price: 15, 
    step: 10, 
    category: 'depressant', 
    onset: 10, 
    offset: 3, 
    toxicity: 5, 
    toleranceRate: 20, 
    toleranceReset: 5, 
    metabolismCurve: 'alcohol', 
    metabolismRate: 1, 
    absorptionRate: 1, 
    beta: 0.15, 
    ka: 6, 
    comedownEnabled: true, 
    comedownDuration: 12, 
    comedownIntensity: 7, 
    comedownSymptoms: ['Bolest hlavy', 'Nevolnost', 'Dehydratace', 'Úzkost'], 
    strains: [
      { name: 'Pivo', price: 12 }, 
      { name: 'Víno', price: 25 }, 
      { name: 'Tvrdý alkohol', price: 40 }
    ], 
    effects: [
      { type: 'Relaxace', intensity: 7, onset: 0.17, duration: 2, valence: 'positive' }, 
      { type: 'Sociabilita', intensity: 6, onset: 0.25, duration: 2, valence: 'positive' }, 
      { type: 'Koordinace', intensity: -6, onset: 0.5, duration: 3, valence: 'negative' }, 
      { type: 'Kognice', intensity: -5, onset: 0.5, duration: 3, valence: 'negative' }
    ], 
    interactions: [], 
    description: 'Centrální depresans' 
  },
  { 
    id: 'kratom', 
    name: 'Kratom', 
    halfLife: 6, 
    tmax: 1.5, 
    bioavailability: 60, 
    color: '#228B22', 
    icon: 'leaf', 
    unit: 'g', 
    price: 15, 
    step: 0.5, 
    category: 'opioid', 
    onset: 20, 
    offset: 4, 
    toxicity: 8, 
    toleranceRate: 18, 
    toleranceReset: 10, 
    metabolismCurve: 'standard', 
    metabolismRate: 1, 
    absorptionRate: 0.8, 
    beta: 0.12, 
    ka: 2, 
    comedownEnabled: true, 
    comedownDuration: 6, 
    comedownIntensity: 5, 
    comedownSymptoms: ['Únava', 'Podrážděnost', 'Bolest'], 
    strains: [
      { name: 'Red Bali', price: 18 }, 
      { name: 'Green Maeng Da', price: 20 }, 
      { name: 'White Borneo', price: 22 }, 
      { name: 'Gold Thai', price: 25 }
    ], 
    effects: [
      { type: 'Bolest', intensity: -7, onset: 0.5, duration: 4, valence: 'positive' }, 
      { type: 'Relaxace', intensity: 6, onset: 0.5, duration: 4, valence: 'positive' }, 
      { type: 'Euphorie', intensity: 5, onset: 0.75, duration: 3, valence: 'positive' }, 
      { type: 'Energie', intensity: 4, onset: 0.5, duration: 3, valence: 'positive' }
    ], 
    interactions: [], 
    description: 'Přírodní opioidní látka' 
  },
  { 
    id: 'melatonin', 
    name: 'Melatonin', 
    halfLife: 0.83, 
    tmax: 0.5, 
    bioavailability: 15, 
    color: '#4B0082', 
    icon: 'moon', 
    unit: 'mg', 
    price: 5, 
    step: 0.5, 
    category: 'supplement', 
    onset: 20, 
    offset: 6, 
    toxicity: 50, 
    toleranceRate: 5, 
    toleranceReset: 1, 
    metabolismCurve: 'standard', 
    metabolismRate: 1, 
    absorptionRate: 1, 
    beta: 0.83, 
    ka: 4, 
    comedownEnabled: false, 
    comedownDuration: 0, 
    comedownIntensity: 0, 
    comedownSymptoms: [], 
    strains: [], 
    effects: [
      { type: 'Spánek', intensity: 7, onset: 0.33, duration: 6, valence: 'positive' }, 
      { type: 'Relaxace', intensity: 6, onset: 0.33, duration: 4, valence: 'positive' }
    ], 
    interactions: [], 
    description: 'Hormon spánku' 
  },
  { 
    id: 'modafinil', 
    name: 'Modafinil', 
    halfLife: 12, 
    tmax: 2, 
    bioavailability: 80, 
    color: '#00CED1', 
    icon: 'zap', 
    unit: 'mg', 
    price: 50, 
    step: 50, 
    category: 'nootropic', 
    onset: 45, 
    offset: 12, 
    toxicity: 8, 
    toleranceRate: 10, 
    toleranceReset: 7, 
    metabolismCurve: 'standard', 
    metabolismRate: 1, 
    absorptionRate: 1, 
    beta: 0.06, 
    ka: 1.5, 
    comedownEnabled: true, 
    comedownDuration: 4, 
    comedownIntensity: 4, 
    comedownSymptoms: ['Únava', 'Bolest hlavy'], 
    strains: [], 
    effects: [
      { type: 'Kognice', intensity: 8, onset: 0.75, duration: 10, valence: 'positive' }, 
      { type: 'BDĚLOST', intensity: 9, onset: 0.75, duration: 12, valence: 'positive' }, 
      { type: 'Motivace', intensity: 7, onset: 1, duration: 8, valence: 'positive' }
    ], 
    interactions: [], 
    description: 'Eugeroikum - podporuje bdělost' 
  },
  { 
    id: 'cbd', 
    name: 'CBD', 
    halfLife: 3, 
    tmax: 2, 
    bioavailability: 20, 
    color: '#228B22', 
    icon: 'cannabis', 
    unit: 'mg', 
    price: 20, 
    step: 10, 
    category: 'cannabinoid', 
    onset: 30, 
    offset: 4, 
    toxicity: 100, 
    toleranceRate: 5, 
    toleranceReset: 3, 
    metabolismCurve: 'standard', 
    metabolismRate: 1, 
    absorptionRate: 1, 
    beta: 0.23, 
    ka: 2, 
    comedownEnabled: false, 
    comedownDuration: 0, 
    comedownIntensity: 0, 
    comedownSymptoms: [], 
    strains: [
      { name: 'Full Spectrum', price: 25 }, 
      { name: 'Isolate', price: 18 }, 
      { name: 'Broad Spectrum', price: 22 }
    ], 
    effects: [
      { type: 'Relaxace', intensity: 6, onset: 0.5, duration: 3, valence: 'positive' }, 
      { type: 'Úzkost', intensity: -5, onset: 0.5, duration: 4, valence: 'positive' }, 
      { type: 'Bolest', intensity: -5, onset: 1, duration: 4, valence: 'positive' }
    ], 
    interactions: [], 
    description: 'Nepsychoaktivní kanabinoid' 
  },
  { 
    id: 'thc', 
    name: 'THC', 
    halfLife: 6, 
    tmax: 0.5, 
    bioavailability: 25, 
    color: '#2E8B57', 
    icon: 'cannabis', 
    unit: 'mg', 
    price: 80, 
    step: 5, 
    category: 'cannabinoid', 
    onset: 5, 
    offset: 3, 
    toxicity: 20, 
    toleranceRate: 30, 
    toleranceReset: 21, 
    metabolismCurve: 'standard', 
    metabolismRate: 1, 
    absorptionRate: 1.5, 
    beta: 0.12, 
    ka: 8, 
    comedownEnabled: true, 
    comedownDuration: 4, 
    comedownIntensity: 3, 
    comedownSymptoms: ['Únava', 'Hlad', 'Sucho v ústech'], 
    strains: [
      { name: 'Indica', price: 90 }, 
      { name: 'Sativa', price: 85 }, 
      { name: 'Hybrid', price: 80 }
    ], 
    effects: [
      { type: 'Euphorie', intensity: 7, onset: 0.1, duration: 2, valence: 'positive' }, 
      { type: 'Relaxace', intensity: 6, onset: 0.25, duration: 3, valence: 'positive' }, 
      { type: 'Kreativita', intensity: 6, onset: 0.5, duration: 2, valence: 'positive' }, 
      { type: 'Chuť k jídlu', intensity: 8, onset: 0.5, duration: 2, valence: 'neutral' }
    ], 
    interactions: [], 
    description: 'Hlavní psychoaktivní kanabinoid' 
  }
];

export const DEFAULT_SETTINGS: UserSettings = { 
  userWeight: 70, 
  userAge: 25, 
  userMetabolism: 'normal', 
  userGender: 'male', 
  timeFormat24h: true, 
  showSeconds: false, 
  compactMode: false, 
  hapticFeedback: true,
  language: 'cs', 
  currency: 'Kč',
  chartWindow: 24, 
  weeklyBudget: 1000,
  chartAnimation: true, 
  chartGrid: true, 
  chartPoints: false, 
  interactionWarnings: true, 
  doseWarnings: true, 
  reminders: false, 
  comedownWarnings: true,
  theme: 'dark'
};

export const DEFAULT_EFFECTS: CustomEffect[] = [
  { name: 'Stimulace', icon: 'zap', color: '#f59e0b', valence: 'positive' }, 
  { name: 'Relaxace', icon: 'cloud', color: '#3b82f6', valence: 'positive' },
  { name: 'Kognice', icon: 'brain', color: '#8b5cf6', valence: 'positive' }, 
  { name: 'Spánek', icon: 'moon', color: '#6366f1', valence: 'positive' },
  { name: 'BDĚLOST', icon: 'eye', color: '#ef4444', valence: 'positive' }, 
  { name: 'Motivace', icon: 'target', color: '#10b981', valence: 'positive' },
  { name: 'Sociabilita', icon: 'users', color: '#f97316', valence: 'positive' }, 
  { name: 'Bolest', icon: 'activity', color: '#ef4444', valence: 'negative' },
  { name: 'Úzkost', icon: 'alert-circle', color: '#8b5cf6', valence: 'negative' }, 
  { name: 'Chuť k jídlu', icon: 'utensils', color: '#22c55e', valence: 'neutral' },
  { name: 'Koordinace', icon: 'move', color: '#06b6d4', valence: 'neutral' }, 
  { name: 'Diuréza', icon: 'droplet', color: '#0ea5e9', valence: 'neutral' },
  { name: 'Euphorie', icon: 'smile', color: '#ec4899', valence: 'positive' }, 
  { name: 'Sedace', icon: 'bed', color: '#64748b', valence: 'neutral' },
  { name: 'Paměť', icon: 'bookmark', color: '#a855f7', valence: 'positive' }, 
  { name: 'Kreativita', icon: 'palette', color: '#f43f5e', valence: 'positive' },
  { name: 'Fokus', icon: 'crosshair', color: '#14b8a6', valence: 'positive' }, 
  { name: 'Energie', icon: 'battery-charging', color: '#eab308', valence: 'positive' },
  { name: 'Nausea', icon: 'frown', color: '#84cc16', valence: 'negative' }, 
  { name: 'Paranoia', icon: 'shield-alert', color: '#dc2626', valence: 'negative' }
];

export const ROUTE_MULTIPLIERS: Record<string, { bioavailability: number, speed: number, tmaxMultiplier: number }> = { 
  oral: { bioavailability: 1.0, speed: 1.0, tmaxMultiplier: 1.0 }, 
  sublingual: { bioavailability: 1.2, speed: 1.5, tmaxMultiplier: 0.5 }, 
  insufflated: { bioavailability: 1.3, speed: 2.0, tmaxMultiplier: 0.3 }, 
  inhaled: { bioavailability: 1.5, speed: 3.0, tmaxMultiplier: 0.15 }, 
  intravenous: { bioavailability: 2.0, speed: 5.0, tmaxMultiplier: 0.05 }, 
  intramuscular: { bioavailability: 1.8, speed: 2.5, tmaxMultiplier: 0.3 }, 
  subcutaneous: { bioavailability: 1.6, speed: 1.8, tmaxMultiplier: 0.5 }, 
  rectal: { bioavailability: 1.4, speed: 1.3, tmaxMultiplier: 0.6 }, 
  topical: { bioavailability: 0.3, speed: 0.5, tmaxMultiplier: 3.0 } 
};

export const STOMACH_MULTIPLIERS: Record<string, { bioavailability: number, speed: number }> = { 
  empty: { bioavailability: 1.2, speed: 1.5 }, 
  light: { bioavailability: 1.0, speed: 1.0 }, 
  full: { bioavailability: 0.9, speed: 0.8 }, 
  heavy: { bioavailability: 0.7, speed: 0.5 } 
};
